### ISSUE TITLE
Query Redirection in folder

### ISSUE THREAD

**Issue by jccaswell** [TPM-Repos/ModifiedCorporateTheme#17]
When auto log in is off in query the user is supposed to be redirected to the login page to put in their credentials. This works if you are running the site on the root of the domain but does not work if you are running it in a folder. 

tpm.com/query?DWConstantData=data would redirect correctly 
but
demo.tpmautomation.com/dev/query?DWConstantData=data would not as it would try and go to root.

**Comment by JosiahDumitrescuTPM** [comment]
I have this working no mater which way it’s done



Josiah Dumitrescu
Technical Solutions Consultant, MFG
Direct: 704.790.5134
Main: 888.313.1688
Linkedin: 

From: Joseph C. Caswell ***@***.***>
Sent: Tuesday, April 30, 2024 5:02 PM
To: TPM-Repos/ModifiedCorporateTheme ***@***.***>
Cc: Josiah Dumitrescu ***@***.***>; Assign ***@***.***>
Subject: [External NOT TPM] [TPM-Repos/ModifiedCorporateTheme] Query Redirection in folder (Issue #17)


When auto log in is off in query the user is supposed to be redirected to the login page to put in their credentials. This works if you are running the site on the root of the domain but does not work if you are running it in a folder.

tpm.com/query?DWConstantData=data would redirect correctly
but
demo.tpmautomation.com/dev/query?DWConstantData=data would not as it would try and go to root.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TPM-2DRepos_ModifiedCorporateTheme_issues_17&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=c6ZQFBCm6juGITRIphiwF8UJOLv9BXLr-K1DILGKhF4&m=6aCfxmYehVZS_T8lJnQYTWcxsR_IGKp1i3wpWcX4hxG9w4yUgfJcm08lxJ98ynTU&s=n9tx6GeO-X4h-7BlJbMsvdDcQIuocaIb6DaNFDnEwzQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A2MP5XD7IBZKPKI36HBQZNTZAABE7AVCNFSM6AAAAABHA7PATSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGI3TENBUGQ2DQNQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=c6ZQFBCm6juGITRIphiwF8UJOLv9BXLr-K1DILGKhF4&m=6aCfxmYehVZS_T8lJnQYTWcxsR_IGKp1i3wpWcX4hxG9w4yUgfJcm08lxJ98ynTU&s=mI-dZ0vPI8u5W-ROoCw_ia8yvWI-OYeNqNAyAQqVv6w&e=>.
You are receiving this because you were assigned.Message ID: ***@***.***>



________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us3.proofpointessentials.com/app/report_spam.php?mod_id=11&mod_option=logitem&report=1&type=easyspam&k=k1&payload=53616c7465645f5fd9579a7b74418ef404eb379d688f38ac504c5b2dcf7d347b918250ed262f2e42102cf11d752f27d083de25c61ffcf971951a4e4e9e29ed22b816d0b1f1b4d4da87ca13ff1337b289855a0f7c00938605835b74b25d81dc815fe3747ad989ca69595078c33371aaa32716704eb40cf171ed5f35af0fc78d3cc302319fd68ef582cb823ea3db2514e8494d1a56fae750534eab272f2494fa5f> to report this email as spam.

**Comment by jccaswell** [comment]
This was fixed in 843642c0f3196ec28aeba5f73bfe23d6e6284b86
