### ISSUE TITLE
Enable multiple query configurations within the same site.

### ISSUE THREAD

**Issue by joelhanneman** [TPM-Repos/ModifiedCorporateTheme#33]
Be able to add multiple query use-cases, presumably by adding more configurations:
![image](https://github.com/TPM-Repos/ModifiedCorporateTheme/assets/160279856/535888d6-10f7-4c44-b84d-ce3e69d8caed)

**Comment by jccaswell** [comment]
This is not necessary. 

Only use queries when you need to autologin. 

Otherwise, you can just pass the parameters directly to run.html
For example: 

```https://templates.tpmautomation.com/query?DWConstantForm=ForgotPassword```
Allows for autologin

```https://templates.tpmautomation.com/run.html?project=AccountManagement&DWConstantForm=ForgotPassword```
Does the exact same thing, but requires you to login first. 

In this case the Constant `Form` has been added to the ConfigUser.xml to allow for edit access. Both for the Alias assigned in `config.GroupAlias` and in the Alias assigned in `config.query.defaultGroupAlias`

```
<permissions>
        <project name="AccountManagement">
          <constant name="Form">
            <team name="Users" canEdit="true"/>
          </constant>
        </project>
      </permissions>
```

Note the word `default` in `defaultGroupAlias` and `defaultProjectName`
These are what is used if the Group Alias and Project name are not passed as parameters. 
It doesn't make sense to have multiple `defaults` 

You can always specify the Alias and Project explicitly

```/query?alias={GroupAlias}&run={ProjectName}```

you can keep passing additional info such as macros or constants be appending additional `&`

```/query?alias=Templates&run=AccountManagement&DWConstantForm=ResetPassword&DWMacroToken=abc-123```

For each alias that you wish to have an autologin, you must provide the username and password in the `sharedGroupAlias` definition

```<sharedGroupAlias name="TemplatesGuest" serverAddress="DWLive" groupName="Templates" username="Guest" password="*********">```
