### ISSUE TITLE
Login page carousel images are not sized (do not resize) properly

### ISSUE THREAD

**Issue by joelhanneman** [TPM-Repos/ModifiedCorporateTheme#51]
Reference: https://niko.tpmautomation.com/

Images taken directly from their website, ex: https://www.nikocranes.com/products/jib-cranes/

Saved image files here: \\DWLive\DWGroupContent\NIKO\Website\dist\img

**Comment by joelhanneman** [comment]
@jccaswell , is this something that is easily fixed?  The images supplied to the website are of no particular size.  Do they need to be or can the website resize them somehow?

**Comment by jccaswell** [comment]
The images resize to the available screen real estate in order to show no white space and not lose their aspect ratio. I do not plan on changing this behavior.

**Comment by joelhanneman** [comment]
To confirm, the solution is to supply images with the correct aspect ratio?

**Comment by jccaswell** [comment]
There is not such thing as a "correct aspect ratio" the aspect ratio of my monitor is different then yours, and different again from our phones. Also, because this is in a browser there is nothing saying that you have to have it open in full screen. 
Consider these examples:
My laptop: 
![image](https://github.com/user-attachments/assets/15d69a2a-51d6-4010-9e98-867e83633827)
Browser not maximized:
![image](https://github.com/user-attachments/assets/f3c19158-afa4-4a04-badf-a63971a84472)
iPad Air:
![image](https://github.com/user-attachments/assets/58c79ef1-d5bf-4008-8426-86562e1fcdf1)

You will notice that the aspect ratio for the space available is different for each. But, there is no white space in any case, and the image doesn't look skewed. 

Let's consider if we forced the entire image to visible: 
Maintain aspect ratio:
![image](https://github.com/user-attachments/assets/c3bc891e-bd70-41ad-98bf-795c522da0cc)
Fill all space:
![image](https://github.com/user-attachments/assets/91150796-6c8f-4967-a282-9c9645fd5b8b)

These alternatives may be preferable if there was specific information we wanted to ensure was shown: but that is not the purpose of the carousel. It is simply there to look pretty and give some branding.
